version: '2'

volumes:
  postgres-data:
    driver: local

services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    command: script/rails server
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db